Enh/schema validation attribute values
simphony/simphony-osp pull request #830
Opened 2022-11-15 15:11 UTC by MBueschelberger

closes #828 

New functionalities for checking the value and length (if it is string) or range (it is a float/int/bool) of a CUDS-attribute.

Please see the updated unittests as reference for this example:

```
city.Citizen:
    city.name:
        STRING:
            length: 1+
            cardinality: 1
    city.age:
        INT:
            range: 0+
            cardinality: 1
```

In the case of a string for an attribute, we can state what should be the length of a `city.name`. For all other types, we can specify the numerical range.

Here is an example of how to restrict a cuds with respect to a certain value, which is very useful for unittesting:

```
city.Citizen:
    city.name:
        STRING:
            value: peter
            cardinality: 1
    city.age:
        INT:
            value: 18
            cardinality: 1
```

Furthermore, the schema validation received an extra keyword-argument called `strict_check` which - as the name already says - triggers a strict check of the cuds during the validation. This basically means that the test fails when any extra cuds apart the ones listed in the schema-file are encountered while querying the root object.

**Please note**: This implementation is closely imitating what is supposed to be covered by any standardized markup-language such as `ottr` or `SHACL`. But due to lack of time in the use case, we could not really focus on integrating these languages into `simphony-osp`, because the effort for translating the schema file into the required shapes was too high.

2022-11-15 15:39 UTC, MBueschelberger commented
@kysrpex , there seems to be some problem with the sqlite-wrapper in the pipeline. I am not sure if this is related to the native `sqlite3`-package from python3.

2022-12-06 13:54 UTC, kysrpex requested changes
Hi @MBueschelberger,

I requested two very minor changes that you can automatically apply just clicking a button on GitHub, if you do it then the PR is good to go.

I am not very happy with the code (and foresee bugs) but this is strongly related to the fact that I am not happy with the original code either. I know that you are just plugging your feature into it and it seems reasonable to me, and the changes do not make things worse. Let's say that I would not be ready to document and promote the whole schema validation feature in its current state (neither was I ready before), but I think this PR is a net positive anyway.

2022-12-06 13:54 UTC, kysrpex commented on osp/core/utils/schema_validation.py
> +        strict_check (bool): whether extra cuds not listed
```suggestion
        strict_check (bool): whether extra cuds not listed in
```

2022-12-06 13:54 UTC, kysrpex commented on osp/core/utils/schema_validation.py
> +                raise ConsistencyError(message)
```suggestion
        if value and attribute != value:
            message = """Found invalid attribute value
            between {} and {} with relationship {}.
            The constraint says it should be valued '{}',
            but we found '{}'. The uid of the affected
            cuds_object is: {}""".format(
                str(origin_cuds.oclass),
                dest_oclass,
                rel_entity,
                value,
                attribute,
                origin_cuds.uid,
            )
            raise ConsistencyError(message)
```

2022-12-07 11:20 UTC, MBueschelberger commented
Why does the pipeline fail again after you merged dev into this branch at commit `d3bc34e2b9ae9d5b88c7fa092ba2071f288fc45d`? The pipeline for commit `1a42f0f6731014c43b8ebc2b4e81963f19a8cfe2` was successful but **not** for the following `15a168c3afcde72fd2094e89ce67afc234155aad`? This is confusing

2022-12-07 12:14 UTC, kysrpex approved these changes

2022-12-07 12:14 UTC, kysrpex commented
> Why does the pipeline fail again after you merged dev into this branch at commit `d3bc34e2b9ae9d5b88c7fa092ba2071f288fc45d`? The pipeline for commit `1a42f0f6731014c43b8ebc2b4e81963f19a8cfe2` was successful but **not** for the following `15a168c3afcde72fd2094e89ce67afc234155aad`? This is confusing

Good question honestly, I will try to find out.

2022-12-07 12:34 UTC, merged